### ISSUE TITLE
AttributeError: module 'types' has no attribute 'ListType'

### ISSUE THREAD

**Issue by jonnyborbs** [denyhosts/denyhosts#193]
Freshly installed via `denyhosts-py37-3.1` port on **FreeBSD 12.1-RELEASE-p6** using `python37-3.7.7_1`

On first startup the following message is thrown:

```Starting denyhosts.
Traceback (most recent call last):
  File "/usr/local/bin/denyhosts.py", line 229, in <module>
    first_time, noemail, daemon, foreground)
  File "/usr/local/lib/python3.7/site-packages/DenyHosts/deny_hosts.py", line 78, in __init__
    offset = self.process_log(logfile, last_offset)
  File "/usr/local/lib/python3.7/site-packages/DenyHosts/deny_hosts.py", line 501, in process_log
    self.__report.add_section(msg, new_denied_hosts)
  File "/usr/local/lib/python3.7/site-packages/DenyHosts/report.py", line 43, in add_section
    if (type(i) is types.ListType) or (type(i) is types.TupleType):
AttributeError: module 'types' has no attribute 'ListType'```

**Comment by josev814** [comment]
This issue was fixed June of 2016.  https://github.com/denyhosts/denyhosts/pull/55/files

I haven't used FreeBSD all that much.  I know they use pkg to manage their software.  I see that it says that it's python3.7 version 3.1.

Are you able to install the package via GitHub/Python or using Docker?
The latest version on GitHub is VERSION = "3.1.2.202005311635".  The Docker instance will pull down the latest Denyhosts version for use when you initially launch it.

**Comment by vaficionado** [comment]
Hey, thanks for the quick response - I forgot to mention that I did find that issue when I was researching initially. I'm not sure why this is still happening, both Python and Denyhosts were installed via the FreeBSD ports collection directly (not pkg, so built from latest source on demand) - pulled `denyhosts-denyhosts-v3.1_GH0.tar.gz`

**Comment by vaficionado** [comment]
Additional build info from the Ports collection:

```
Port:	denyhosts-py37-3.1
Path:	/usr/ports/security/denyhosts
Info:	Script to thwart ssh and imap attacks
Maint:	sunpoet@FreeBSD.org
B-deps:	gettext-runtime-0.20.2 indexinfo-0.3.1 libffi-3.2.1_3 libiconv-1.16 ncurses-6.1.20190525 py27-ipaddr-2.2.0 py36-setuptools-44.0.0 python27-2.7.18 python36-3.6.10 python37-3.7.7_1 readline-8.0.4
R-deps:	gettext-runtime-0.20.2 indexinfo-0.3.1 libffi-3.2.1_3 libiconv-1.16 ncurses-6.1.20190525 py27-ipaddr-2.2.0 py36-setuptools-44.0.0 python27-2.7.18 python36-3.6.10 python37-3.7.7_1 readline-8.0.4
WWW:	https://github.com/denyhosts/denyhosts```

**Comment by josev814** [comment]
I was able to find similar information from the freshports site:  https://www.freshports.org/security/denyhosts/
I'll have to check the release tgz file, and see if that needs to be updated.

**Comment by vaficionado** [comment]
Roger that, would be much appreciated. It looks like the merge from that PR above might have landed in a beta build that wasn't cut as an official release.

**Comment by josev814** [comment]
Yeah, the Source Code (tar.gz) has old code of when 3.1 Beta was first released, but the tar.gz file is a more recent build.  So, more than likely I'll have to create a new release in order for the more recent source code to get picked up.

**Comment by vaficionado** [comment]
Should mention: if you need anything getting the updated release tarball into the ports collection, I know someone who's willing to lend a hand 😄

**Comment by josev814** [comment]
That'll be helpful.  I just want to fix a couple of bugs before pushing a
new release.

**Comment by vaficionado** [comment]
Hiya! Just bumping this one. Any movement towards a new release?
